### PR TITLE
Fixed reference to offsetHeight

### PR DESCRIPTION
**Pull request by b4r7**
Had some issues with coordinates not matching up, traced it down to a reference to offsetWidth where it should be offsetHeight.

### CODE REVIEW

**Comment by gruhn** [comment]
Wow, no idea how that slipped through. 

Can you adjust your commit message though? It must comply with [Angular Commit Message Conventions](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines) because an NPM release is automatically published based on the commit message.

Something like:
```
fix(QrcodeStream): reference to offsetHeight
```

**Comment by b4r7** [comment]
Yes, will do. Thank you for the great plugin btw!

**Comment by gruhn** [comment]
You still want to do this? Otherwise I'll quickly do it :relaxed:

**Comment by b4r7** [comment]
Yeah just go ahead, editing the commit message was a bit complicated so I
put it off. I'm building an app on a deadline ;)

**Pull request merged**
