### PR TITLE
added reset content in paused watch

### PR DESCRIPTION
**Pull request by gewra**
Had to add a setTimeout so that the same qr-image would not be scanned from the frozen video stream. 
Have a look-see if it's something you'd be willing to use

### CODE REVIEW

**Comment by gruhn** [comment]
Sorry, this took way too long...

I should have mentioned we're using ESLint. Can you fix those ESLint errors? If you need help, just ask.

**Comment by gewra** [comment]
No worries!
Sorry bout that, been switching between computers and OS:es and in this particular editor vue-files wasn't added to the eslint-config, apparently.

**Comment by gruhn** [comment]
Thanks! I'll setup a demo and report back

**Pull request merged**
