### PR TITLE
Implements support for inverted QR codes

### PR DESCRIPTION
**Pull request by thomas-alrek**

### CODE REVIEW

**Comment by nabenzine** [comment]
Amazing feature, I've been waiting for this for so long, why isn't it merged yet ? it is because merge conflict ? or the repo athor didn't accept it yet.

Thx

**Comment by thomas-alrek** [comment]
I'm bumping this, since it has been a while since this PR was submitted.

**Comment by thomas-alrek** [comment]
Bump

**Comment by gruhn** [comment]
Should work now.

**Pull request closed without merging**
