### PR TITLE
fix: Turn off torch on exit

### PR DESCRIPTION
**Pull request by gruhn**
See: #380

### CODE REVIEW

**Comment by ebisbe** [comment]
On my Xiaomi it's still not turning off the torch. 

https://github.com/gruhn/vue-qrcode-reader/assets/6747962/5a2a246e-7ae3-4a8c-9af7-9e0241468d25

**Comment by gruhn** [comment]
@ebisbe @alexandrmucha can you check [the deploy preview](https://deploy-preview-383--vue-qrcode-reader.netlify.app/) again?

**Comment by alexandrmucha** [comment]
Now it works perfectly, you can switch between cameras and the flash turns off correctly. Thanks!

**Comment by gruhn** [comment]
Credit goes to @Sec-ant :)

**Pull request merged**
