### PR TITLE
added: torch prop

### PR DESCRIPTION
**Pull request by magyarb**
Now the torch prop works, and turns on the torch when the prop value is true.
The setTimeout solution is not nice, but without that it throws an exception.

### CODE REVIEW

**Comment by gruhn** [comment]
Hey @magyarb thank you for your contribution. Please read my comment on this matter: https://github.com/gruhn/vue-qrcode-reader/issues/112#issuecomment-490587825

I'm not convinced this is the way to go here. Do you require this feature too? If so please elaborate your use case :)

**Comment by magyarb** [comment]
My use case is reading QR codes (concert tickets) that are sometimes printed on paper. The lighting conditions are not always perfect, especially at night or indoors. Since almost all of the smartphones have a torch, it would be a bad idea not to use it (and buy a separate lamp to light QR codes). My solution fails silently on devices that do not have a torch, like a webcam.

Maybe if you could improve the setTimeout part, that would be great. For some reason it must wait to something like a process.nextTick(), and it is not enough to await the Camera.

**Comment by gruhn** [comment]
Oh yeah ok, this kind of use case makes sense to me. Thanks for making that clear. I'll take care of the rest.

**Comment by gruhn** [comment]
It looks like you can light the torch on the fly but you can't turn it OFF without stopping the current video track. Can you confirm that? 

Also, I can't reproduce your issue without the timeout. What exactly are the exceptions saying?

**Comment by magyarb** [comment]
I can confirm that calling `applyConstraints({advanced: [{torch: false}]})` does not turn the flash off.
That is the reason for the watcher, that reinitializes the stream on prop change. It happens quite fast.

Device: Xiaomi Redmi 5 plus
Browser: com.brave.browser (74.0.3729.157)

If I change
```
if(this.torch) setTimeout(function(){
          this.cameraInstance.stream.getVideoTracks()[0].applyConstraints({
            advanced: [{torch: true}]
          });
        }.bind(this), 1);
```

To the following:

```
if(this.torch) this.cameraInstance.stream.getVideoTracks()[0].applyConstraints({
            advanced: [{torch: true}]
          }).catch(function(ex){
            console.log(ex)
          });
```

The console prints DOMException, and the torch does not turn on. That's all.

But I've just tried the Chrome browser, and it works on that. It's strange, since Brave is built on Chrome, even the version is the same. But since everyone uses Chrome, Brave support is not essential.

**Comment by magyarb** [comment]
Is there any reason why this isn't merged yet?

**Comment by gruhn** [comment]
@magyarb I dislike that the camera has to be reloaded when you want to turn the torch OFF. If you register a listener for the `init` event, it's called every time the camera is turned OFF. This is pretty unexpected and also inconsistent behavior. _"Why would the camera have to be reloaded, when I turn OFF the torch? And why is this not the case when I'm turning it ON?"_

**Comment by magyarb** [comment]
This is an issue in the Media Streams API, we can not do much unless chrome devs change this behavior . But a camera reload at the torch off event is a small issue compared to not being able to use the torch at all.
Anyway, I also need the feature of selecting the camera from a list, so I will fork this repo.

**Comment by gruhn** [comment]
I know we can't do anything about it. In my opinion a small issue that potentially affects many users is worse than leaving out a feature that some users require. 

I'm really sorry the current version is not sufficient for you :pensive: of course you're always free to fork.

**Comment by liho98** [comment]
hello @magyarb, i have copy your code to vue-qrcode-reader/src/components/QrcodeStream.vue. 

In my code, i tend to initiate the torchlight by this command `button :torch="torch" @init="onInit" class="switch">On / Off</button>`

But, nothing happend, do you know why?

**Comment by magyarb** [comment]
This repo changed a lot since this PR. Maybe i will create a flash/camera switch feature in a new fork from the current version.

The flash does not work on ios and on some browsers. Try chrome on android.

**Comment by liho98** [comment]
> This repo changed a lot since this PR. Maybe i will create a flash/camera switch feature in a new fork from the current version.
> 
> The flash does not work on ios and on some browsers. Try chrome on android.

Thanks, looking forward to it

**Comment by gruhn** [comment]
The `torch` prop is available now but the camera stream is reloaded when the torch is turned OFF AND when it's turned ON. That way the behavior is at least consistent.

**Pull request closed without merging**
