### PR TITLE
Migrate from jsQR to quirc-js

### PR DESCRIPTION
**Pull request by gruhn**
see #4

### CODE REVIEW

**Comment by gruhn** [comment]
@tigranbs I'm glad I can help. Also thanks for this insight.

@rajagopalx This attempt to migrate caused some bad memory leaks in my environment and I haven't found out why yet. Unfortunately, `quirc-js` has very little documentation and is also hard to elegantly merry with Vue due it's highly imperative API. This is abandoned but I don't have a lot of time to work on `vue-qrcode-reader`. I welcome any help though :)

**Comment by rhinck** [comment]
@gruhn I just started learning how to code a few weeks ago and I'm currently developing a PWA for our organization. Your Vue QR reader is one of the main components of our app. I just wanted to thank you for all of your work!

I do have a question though. The framerates on the mobile version of our app is kind of choppy when using the QR reader. Is this a problem with my implementation or does the QR scanner traditionally run a little bit slower on mobile?

**Comment by gruhn** [comment]
Thank you too for your support :grinning: 

Are you referring to the camera streams framerate or the framerate of location points being painted on top of the stream? 

The latter is definitely a problem on our side and also a subject of this pull request. I hope this can be vastly improved in the future.

If you mean the framerate of the camera stream, you should compare it with the demo page on your device and open a dedicated issue here.

Enjoy coding :wink:

**Comment by rhinck** [comment]
@gruhn Sorry for the slow response! I'm probably going to get pretty decent at coding based on the amount of mistakes I've already made :P

 I was previously referring to the camera stream's framerate. I followed your suggestions and compared it to the demo version online and my app's implementation was a little bit slower but not horribly so. I was testing the app on a mobile version of Chrome on a Samsung 2017 J3. Not the best device as far as tech specs goes I guess.

However, once I tested the QR reader on desktop and the iPhone X the performance was very smooth.

Thanks again!

**Comment by qnp** [comment]
What about this PR ? does #114, allowing the use of other decode plugins (so such as quirc-js) means that this PR is no longer usefull ?

**Comment by gruhn** [comment]
@qnp yes 🙂 I'll keep it open though for reference, until we're done.

**Comment by qnp** [comment]
I think we can close this, since https://github.com/gruhn/vue-qrcode-reader/pull/114#issuecomment-534749827

**Pull request closed without merging**
