### PR TITLE
Allow deviceID to use in QrcodeStream

### PR DESCRIPTION
**Pull request by snsanich**
We use the library for mobile and application solution. To support several cameras on computer I added deviceID in the library.

We have #111 request to add the feature. Please, review the code and accept it in your project.

Thanks.

### CODE REVIEW

**Comment by gruhn** [comment]
Hey @snsanich, thank you for taking the time and contributing to vue-qrcode-reader. 

I know adding a single prop looks like a trivial change. However, people frequently request adding props and events (e.g. #15, #117, #112, #109). Adding all these over time piles up to significant internal and API-level complexity. This in turn 

* makes the component more error prone
* introduces burden for backwards-compatibility and makes the component 

Please use the thread at #111 to elaborate your use case. Convince me this is a crucial change that will benefit many most users or maybe we can find a solution that doesn't require API changes

**Comment by snsanich** [comment]
I faced today an error.

error.name === 'OverconstrainedError',

When I tried to set camera to "rear" on my laptop.

**Comment by gruhn** [comment]
Check this demo

https://gruhn.github.io/vue-qrcode-reader/demos/SwitchCamera.html

this is exactly the error you should get if there is no rear camera on your laptop.

**Comment by snsanich** [comment]
You right, but I want to support several cameras on one computer. In such conditions What am I suppose to do with current configuration of QrcodeStream?

**Comment by araimbekoff** [comment]
Hi!

Now phones use several cameras on both sides.
In many phones (for example, Huawei Mate 20 pro), the rear of the telescope camera is turned on by default.
I need the ability to set the camera by device ID, because I know the camera ID with normal zoom


Heeeelp!!!!

**Pull request closed without merging**
