### PR TITLE
Integrate DataMatrix Reader from Zxingjs

### PR DESCRIPTION
**Pull request by sergiocarracedo**
Integrate [ZXing-js/library](https://github.com/zxing-js/library) to allow vue-qrcoder-reader to decode datamatrix codes.

### CODE REVIEW

**Comment by gruhn** [comment]
Hey, thanks for your contribution. 

Looks like this library weighs in with another 50kb. It can process QR codes too though. If it's at least as performant as jsQR, maybe we could replace it.

**Comment by gruhn** [comment]
Hmmm, I'm not sure since I haven't found an exhaustive documentation, but it looks like this library doesn't provide any location information.  This would be an essential feature for this component. 

Also, we should definitely rely on a single library for scanning whatever types of codes. For once to avoid bloat but also to avoid this kind of stuff:

* process with qrcode-library. No result? Well then...
* process with barcode-library. No result? Well then...
* process with datamatrix-library. No result? Well then...

This seems to me like a lot of work that has to be done for each scanned frame.

**Comment by sergiocarracedo** [comment]
Maybe would allow programmers to insert own workers to allow them to process code types they need. 
For example for Zxing will be easier to implement pass camera device id to worker instead frame.

**Comment by LRipi** [comment]
Re-up this old topic.
Really interested by this features.

**Comment by gruhn** [comment]
In principle, it can be done with the still experimental `worker` prop (check out the API docs). It's not very convenient yet but if you're willing to take the effort I'd appreciate feedback.

**Pull request closed without merging**
